name: deploy

on:
  push:
    branches:
      - step2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm i

      - name: Create .env file
        run: |
          echo REACT_APP_BACKEND_URL_KIM_TAEYUN=${{ secrets.REACT_APP_BACKEND_URL_KIM_TAEYUN }} > .env
          echo REACT_APP_BACKEND_URL_KANG_SUMIN=${{ secrets.REACT_APP_BACKEND_URL_KANG_SUMIN }} >> .env
          echo REACT_APP_BACKEND_URL_YOO_KYUNGMI=${{ secrets.REACT_APP_BACKEND_URL_YOO_KYUNGMI }} >> .env

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages